title: Summary of SE for AI Research
email: gujzulto@gmail.com
description: share research work on software engineering for AI applications (especially deep learning)

github_username: ulto777

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
